version: '3.8'

services:
  nginx:
    image: docker.io/library/nginx:latest
    container_name: nginx-server
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - certbot # Ensure certbot runs first

  certbot:
    image: docker.io/certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c"]
    command: "mkdir -p /var/www/certbot && certbot certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d test.lightring.tech > /var/log/certbot.log 2>&1 || trap exit TERM; while :; do sleep 1; done"
