version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Optional: Mount a custom Nginx configuration file
    restart: always # Ensure the container restarts automatically
